### ISSUE TITLE
Travis CI test fails

### ISSUE THREAD

**Issue by wkentaro** [pfnet/chainer#1040]
The test fails on the master branch.
Anyone who knows how to fix this?

https://travis-ci.org/pfnet/chainer/builds/117092179

**TravisConfig**
```
PYTHON_VERSION=2.7.10 PYENV_ROOT=~/.pyenv PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
```

**Error**
```

cython path:/Users/travis/.pyenv/versions/2.7.10/lib/python2.7/site-packages

error: Command '/Users/travis/.pyenv/versions/2.7.10/bin/python' failed:



  command: /Users/travis/.pyenv/versions/2.7.10/bin/python /Users/travis/.pyenv/versions/2.7.10/lib/python2.7/site-packages/cython.py --version

  return code: 1

  output:



Traceback (most recent call last):

  File "/Users/travis/.pyenv/versions/2.7.10/lib/python2.7/site-packages/cython.py", line 16, in 

    from Cython.Compiler.Main import main

  File "/Users/travis/.pyenv/versions/2.7.10/lib/python2.7/site-packages/Cython/Compiler/Main.py", line 28, in 

    from .Scanning import PyrexScanner, FileSourceDescriptor

ImportError: dlopen(/Users/travis/.pyenv/versions/2.7.10/lib/python2.7/site-packages/Cython/Compiler/Scanning.so, 2): Symbol not found: _PyUnicodeUCS2_Compare

  Referenced from: /Users/travis/.pyenv/versions/2.7.10/lib/python2.7/site-packages/Cython/Compiler/Scanning.so

  Expected in: flat namespace

 in /Users/travis/.pyenv/versions/2.7.10/lib/python2.7/site-packages/Cython/Compiler/Scanning.so






travis_time:end:047d8f6a:start=1458384727000000000,finish=1458384727000000000,duration=0


The command "python setup.py sdist" failed and exited with 1 during .
```

**Comment by unnonouno** [comment]
Maybe cython wheel file in pypi for python 2.7 on OSX is built with ucs-2, and pyenv on OSX builds python 2.7.10 with ucs-4. I fixed travis config.
