### ISSUE TITLE
Error of max_pooling_2d on CPU

### ISSUE THREAD

**Issue by mitmul** [pfnet/chainer#120]
I gave a same value for the kernel size and stride on `average_pooling_2d` and `max_pooling_2d`, and I changed the value to be ranged from 1 to 99 for 100 x 100 x 3 images. Then, in the case of `average_pooling_2d`, there are no errors at all values, but in the case of `max_pooling_2d`, a numpy related error raised when the value is 6. The error doesn't come up on GPU. It happens only on CPU. (but I'm not sure in the case without cuDNN)

Test code:
```
import numpy
import chainer.functions as F
from chainer import Variable, cuda

x = numpy.random.rand(10, 3, 100, 100).astype(numpy.float32)

# when on GPU, there's no problem!
# cuda.init()
# x = cuda.to_gpu(x)

x = Variable(x)

# OK on both GPU and CPU
for i in range(1, 100):
    print('ave:', i,
          F.average_pooling_2d(x, ksize=i, stride=i, pad=0).data.shape)

# ERROR on CPU
for i in range(1, 100):
    print('max:', i,
          F.max_pooling_2d(x, ksize=i, stride=i, pad=0).data.shape)
```

Output (on CPU):
```
:
:
:
('ave:', 95, (10, 3, 1, 1))
('ave:', 96, (10, 3, 1, 1))
('ave:', 97, (10, 3, 1, 1))
('ave:', 98, (10, 3, 1, 1))
('ave:', 99, (10, 3, 1, 1))
('max:', 1, (10, 3, 100, 100))
('max:', 2, (10, 3, 50, 50))
('max:', 3, (10, 3, 34, 34))
('max:', 4, (10, 3, 25, 25))
('max:', 5, (10, 3, 20, 20))
Traceback (most recent call last):
  File "tests/test_pool.py", line 16, in <module>
    F.max_pooling_2d(x, ksize=i, stride=i, pad=0).data.shape)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/chainer_cuda_deps-1.0.0-py2.7.egg/chainer/functions/pooling_2d.py", line 210, in max_pooling_2d
    return MaxPooling2D(ksize, stride, pad, cover_all, use_cudnn)(x)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/chainer_cuda_deps-1.0.0-py2.7.egg/chainer/function.py", line 158, in __call__
    outputs = self.forward(in_data)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/chainer_cuda_deps-1.0.0-py2.7.egg/chainer/function.py", line 195, in forward
    return self.forward_cpu(inputs)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/chainer_cuda_deps-1.0.0-py2.7.egg/chainer/functions/pooling_2d.py", line 77, in forward_cpu
    y = self.indexes.choose(col)
ValueError: Need between 2 and (32) array objects (inclusive).
```

**Comment by beam2d** [comment]
Thank you for reporting the bug. I succeeded to reproduce the bug. We will investigate the error.

**Comment by beam2d** [comment]
I made a patch for this issue. It should be merged soon.

**Comment by delta2323** [comment]
close #120 via #125

**Comment by delta2323** [comment]
close #120 via #125
