### ISSUE TITLE
Saved state of Adam cannot be deserialized

### ISSUE THREAD

**Issue by mitmul** [pfnet/chainer#1264]
For example, using a saved state that is generated by the official MNIST example (examples/mnist/train_mnist.py), 

```
from chainer import optimizers
from chainer import serializers
opt = optimizers.Adam()
serializers.load_npz('mlp.state', opt)
```

the blow error occurs:

```
Traceback (most recent call last):
  File "adam.py", line 4, in <module>
    serializers.load_npz('mlp.state', opt)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/chainer-1.9.0-py3.5-macosx-10.5-x86_64.egg/chainer/serializers/npz.py", line 119, in load_npz
    d.load(obj)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/chainer-1.9.0-py3.5-macosx-10.5-x86_64.egg/chainer/serializer.py", line 79, in load
    obj.serialize(self)
  File "/usr/local/var/pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/chainer-1.9.0-py3.5-macosx-10.5-x86_64.egg/chainer/optimizer.py", line 250, in serialize
    self.t = serializer('t', self.t)
AttributeError: 'Adam' object has no attribute 't'
```

Is this a bug or wrong usage? I'd appreciate it if anyone could provide a solution (or fix it :P)

**Comment by mitmul** [comment]
Sorry it works after performing `setup`

```
import chainer
from chainer import optimizers
from chainer import serializers
model = chainer.Chain()
opt = optimizers.Adam()
opt.setup(model)
serializers.load_npz('mlp.state', opt)
```
