### ISSUE TITLE
Nested exception occurs on type error on using Python3

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#1552]
When a type error occurs in type-check, Chainer raises a nested error when a user uses Python3 and shows the message:
```
During handling of the above exception, another exception occurred:
```

**Comment by gwtnb** [comment]
Could you paste a more informative error message?

**Comment by unnonouno** [comment]
```>>> chainer.functions.concat([numpy.array([1]), numpy.array([1,2])])
Traceback (most recent call last):
  File "/home/unno/git/chainer/chainer/function.py", line 191, in _check_data_type_forward
    self.check_type_forward(in_type)
  File "/home/unno/git/chainer/chainer/functions/array/concat.py", line 22, in check_type_forward
    type_check.Variable(self.axis, 'axis'))
  File "/home/unno/git/chainer/chainer/utils/type_check.py", line 466, in expect
    expr.expect()
  File "/home/unno/git/chainer/chainer/utils/type_check.py", line 436, in expect
    '{0} {1} {2}'.format(left, self.inv, right))
chainer.utils.type_check.InvalidType: Expect: in_types[0].ndim > axis
Actual: 1 <= 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/unno/git/chainer/chainer/functions/array/concat.py", line 64, in concat
    return Concat(axis=axis)(*xs)
  File "/home/unno/git/chainer/chainer/function.py", line 122, in __call__
    self._check_data_type_forward(in_data)
  File "/home/unno/git/chainer/chainer/function.py", line 197, in _check_data_type_forward
    raise type_check.InvalidType(e.expect, e.actual, msg=msg)
chainer.utils.type_check.InvalidType:
Invalid operation is performed in: Concat (Forward)

Expect: in_types[0].ndim > axis
Actual: 1 <= 1```

**Comment by gwtnb** [comment]
Thanks
