### ISSUE TITLE
New convolution algorithm in cuDNN 5.1

### ISSUE THREAD

**Issue by 6o6o** [pfnet/chainer#1610]
Hi.

cuDNN 5.1 implements a faster convolution algorithm which offers a significant speedup of 2-3 times for small kernel operations according to NVIDIA https://developer.nvidia.com/cudnn

I tried forcing Chainer to choose the `CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED` when making a decision in `Convolution2DFunction` definition, but get an error:

```
Traceback (most recent call last):
  File "train.py", line 100, in <module>
    feature_s = vgg(Variable(style_b, volatile=True))
  File "/home/dnn/fast-neuralstyle/net.py", line 96, in __call__
    y1 = F.relu(self.conv1_2(F.relu(self.conv1_1(x))))
  File "/usr/lib64/python2.7/site-packages/chainer/links/connection/convolution_2d.py", line 96, in __call__
    x, self.W, self.b, self.stride, self.pad, self.use_cudnn)
  File "/usr/lib64/python2.7/site-packages/chainer/functions/connection/convolution_2d.py", line 318, in convolution_2d
    return func(x, W, b)
  File "/usr/lib64/python2.7/site-packages/chainer/function.py", line 130, in __call__
    outputs = self.forward(in_data)
  File "/usr/lib64/python2.7/site-packages/chainer/function.py", line 234, in forward
    return self.forward_gpu(inputs)
  File "/usr/lib64/python2.7/site-packages/chainer/functions/connection/convolution_2d.py", line 122, in forward_gpu
    y_desc.value, y.data.ptr)
  File "cupy/cuda/cudnn.pyx", line 442, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:5139)
  File "cupy/cuda/cudnn.pyx", line 454, in cupy.cuda.cudnn.convolutionForward (cupy/cuda/cudnn.cpp:4951)
  File "cupy/cuda/cudnn.pyx", line 243, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:1499)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_INVALID_VALUE: CUDNN_STATUS_INVALID_VALUE
```

Is there any way to make this work? Really eager to try this out.
Thanks.

**Comment by unnonouno** [comment]
Hum. I checked the cuDNN document, and found that `CUDNN_STATUS_INVALID_VALUE` is not expected to be raised with this API. I couldn't find its reason.

Please check this list:
- Did you recompile or reinstall Chainer after you install the new cuDNN? ABI is not compatible between different versions of cuDNNs.
- Please check the condition for `CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED` written in the document:
```
xDesc Format Support: All
‣ yDesc Format Support: All
‣ Data Type Config Support: All except DOUBLE_CONFIG
‣ Notes:
‣ convDesc's vertical and horizontal filter stride must equal 1
‣ wDesc's filter (height, width) must be (3,3) or (5,5)
‣ If wDesc's filter (height, width) is (5,5), data type config
TRUE_HALF_CONFIG is not supported
```
- The stride must be 1, and the kernel size must be (3, 3) or (5, 5)

**Comment by niboshi** [comment]
Closing the issue. Please reopen if the problem persists.
