### ISSUE TITLE
examples/ptb error on macOS 10.12

### ISSUE THREAD

**Issue by chenzhekl** [pfnet/chainer#1734]
This is my environment setting.
1. Python: 3.5.2
2. numpy: 1.11.1 (installed with openblas)
3. chainer: 1.16.0

After running `python train_ptb.py`, I got the following message.

```
#vocab = 10000
Traceback (most recent call last):
  File "/Users/chenzhekl/Downloads/train_ptb.py", line 240, in <module>
    main()
  File "/Users/chenzhekl/Downloads/train_ptb.py", line 191, in main
    rnn = RNNForLM(n_vocab, args.unit)
  File "/Users/chenzhekl/Downloads/train_ptb.py", line 26, in __init__
    embed=L.EmbedID(n_vocab, n_units),
  File "/Users/chenzhekl/workspace/fish/venv/lib/python3.5/site-packages/chainer/links/connection/embed_id.py", line 34, in __init__
    super(EmbedID, self).__init__(W=(in_size, out_size))
  File "/Users/chenzhekl/workspace/fish/venv/lib/python3.5/site-packages/chainer/link.py", line 128, in __init__
    self.add_param(name, shape, dtype=dtype)
  File "/Users/chenzhekl/workspace/fish/venv/lib/python3.5/site-packages/chainer/link.py", line 173, in add_param
    data = self.xp.full(shape, numpy.nan, dtype=dtype)
  File "/Users/chenzhekl/workspace/fish/venv/lib/python3.5/site-packages/numpy/core/numeric.py", line 297, in full
    a = empty(shape, dtype, order)
TypeError: data type not understood
```

**Comment by bkvogel** [comment]
Hi,
That error should now be fixed in the master branch.

**Comment by chenzhekl** [comment]
Chainer 1.17.0 fixes it.
