### ISSUE TITLE
cudnn.check_status raises CuDNNError CUDNN_STATUS_NOT_SUPPORTED on BatchNormalizationFunction

### ISSUE THREAD

**Issue by knok** [pfnet/chainer#1762]
On the follwing environment:
Linux Debian 8.5 (linux 3.16.7)
CUDA 7.5.18
CuDNN 5.1

I tried to run the code on https://github.com/musyoku/variational-autoencoder
M1/train.py works fine, but M1/visualization.py causes the following error:
```
Traceback (most recent call last):
  File "visualize.py", line 28, in <module>
    z = vae.encoder(x, test=True)
  File "/home/knok/ml/variational-autoencoder/vae_m1.py", line 389, in __call__
    mean, ln_var = self.forward_one_step(x, test=test, apply_f=apply_f)
  File "/home/knok/ml/variational-autoencoder/vae_m1.py", line 368, in forward_o
ne_step
    u = getattr(self, "batchnorm_%d" % i)(u, test=test)
  File "/opt/gpu/local/lib/python2.7/site-packages/chainer-1.9.1-py2.7-linux-x86
_64.egg/chainer/links/normalization/batch_normalization.py", line 137, in __call
__
    x, gamma, beta, self.avg_mean, self.avg_var, self.eps)
  File "/opt/gpu/local/lib/python2.7/site-packages/chainer-1.9.1-py2.7-linux-x86_64.egg/chainer/functions/normalization/batch_normalization.py", line 318, in fixed_batch_normalization
    return BatchNormalizationFunction(fixed_mean, fixed_var, False, 0.0, eps)(x, gamma, beta)
  File "/opt/gpu/local/lib/python2.7/site-packages/chainer-1.9.1-py2.7-linux-x86_64.egg/chainer/function.py", line 130, in __call__
    outputs = self.forward(in_data)
  File "/opt/gpu/local/lib/python2.7/site-packages/chainer-1.9.1-py2.7-linux-x86_64.egg/chainer/functions/normalization/batch_normalization.py", line 150, in forward
    self.eps)
  File "cupy/cuda/cudnn.pyx", line 650, in cupy.cuda.cudnn.batchNormalizationForwardInference (cupy/cuda/cudnn.cpp:8626)
  File "cupy/cuda/cudnn.pyx", line 664, in cupy.cuda.cudnn.batchNormalizationForwardInference (cupy/cuda/cudnn.cpp:8429)
  File "cupy/cuda/cudnn.pyx", line 239, in cupy.cuda.cudnn.check_status (cupy/cuda/cudnn.cpp:1497)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_NOT_SUPPORTED: CUDNN_STATUS_NOT_SUPPORTED 
```

At least v1.9.0 works fine and v1.16.0 not works so I tried to run git bisect and the result:
```
knok@kdebian ~/chainer/git % git bisect good
cfa2956e178147cfc611debd2c6b0fb1935b8d32 is the first bad commit
commit cfa2956e178147cfc611debd2c6b0fb1935b8d32
Author: Brian Vogel <vogel@preferred.jp>
Date:   Thu Jun 23 11:44:02 2016 +0900

    cuDNN-optimized batch normalization function and link added.

:040000 040000 963aaf0bbc7d4184f4282d1882c18b272d762177 46f1cd47068169b1e0062cdcdfc440a58b03537e M	chainer
:040000 040000 361bac2c8258aef0c341059ae3caa1aed18d2f4e 2ae79f972734dd87c0f9ff02fb784688567ef5d4 M	tests
```

Can I use BatchNormalizationFunction with cudnn on  CUDA 7.5 + CuDNN 5.1 ?

**Comment by delta2323** [comment]
Thank you for reporting the problem. I investigate the problem, but unfortunately, cannot reproduce the problem for now.

In my environment (CUDA 7.5, cuDNN 5.1), the following code works. I confirmed the program surely runs [here](https://github.com/pfnet/chainer/blob/master/chainer/functions/normalization/batch_normalization.py#L152).

```
import chainer
from chainer import links as L
import cupy
print(chainer.cuda.cudnn.cudnn.getVersion()) # =>5103 
x = cupy.random.uniform(size=(10, 5)).astype(cupy.float32)
x = chainer.Variable(x)
l = L.BatchNormalization(5)
l.to_gpu()
l(x, test=True)
```

**Comment by knok** [comment]
Thank you for your respond.
On my environment, visualize.py still not work, but the avobe code works fine.
It would be something wrong in my environment. I'll try to find the reason, and if I will find, reopen this.

**Comment by knok** [comment]
At least, my environment with nvidia-docker container, the issue is not reproduced.
It seems my environment issue.

**Comment by knok** [comment]
Finally, I can fixed this problem by the following step:

* uninstall chainer
* upgrade pip
* install chainer
* remove ~/.cupy/*
