### ISSUE TITLE
User defined kernel with fully manual indexing

### ISSUE THREAD

**Issue by anaruse** [pfnet/chainer#1802]
I'm trying to create some user defined kernels with fully manual indexing, but I get error as follows. According to the error message, seems it can not decide size of output array, though I set the size argument at the invocation. Is there anything wrong in my code sample?

```
test_kernel_1 = cupy.ElementwiseKernel(
    'raw T x, raw T y',
    'raw T z',
    '''                                                                                              
        z[i] = x[i] + y[i];                                                                          
    ''',
    'test_kernel_1' )
x1 = chainer.Variable( cupy.random.uniform(-1, 1, 5).astype(cupy.float32) )
x2 = chainer.Variable( cupy.random.uniform(-1, 1, 5).astype(cupy.float32) )
x1.to_gpu()
x2.to_gpu()
x3 = test_kernel_1( x1.data, x2.data, size=5 )
```

> Traceback (most recent call last):
>   File "test_cupy-user-kernel.py", line 19, in <module>
>     x3 = test_kernel_1( x1.data, x2.data, size=5 )
>   File "cupy/core/elementwise.pxi", line 527, in cupy.core.core.ElementwiseKernel.**call** (cupy/core/core.cpp:35988)
>   File "cupy/core/elementwise.pxi", line 374, in cupy.core.core._get_out_args_with_params (cupy/core/core.cpp:33826)
> **ValueError: Output array size is Undecided**

**Comment by anaruse** [comment]
I found the cause. I will send a PR later.
