### ISSUE TITLE
weight_decay hook fails when CUDA is available but no device is detected

### ISSUE THREAD

**Issue by fquivira** [pfnet/chainer#1944]
I have a simple network I'm trying to train with AdaGrad. I added the weight decay hook by using: 

`optimizer.add_hook(chainer.optimizer.WeightDecay(weight_decay))`

However, I get an error that no CUDA-capable device is detected when I try to run the trainer even though all computation should be on the CPU. If I remove weight decay hook, my code runs fine.

I think the error is in line 492 in optimizer.py:
```
if cuda.available:
            kernel = cuda.elementwise(
                'T p, T decay', 'T g', 'g += decay * p', 'weight_decay')
```
I think it checks only if cuda is available but not if the device is to be used like below (line 498 in optimizer.py): 
```
            with cuda.get_device(p) as dev:
                if int(dev) == -1:
                    g += rate * p
                else:
                    kernel(p, rate, g)
```

I'm running on Windows 8.1 with CUDA 8.0 and Chainer 1.18.

**Comment by delta2323** [comment]
Hi, thank you for reporting the problem. Could you share the stack trace to see the error message?

**Comment by fquivira** [comment]
Yup. Here it is:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\training\trainer.py", line 292, in run
    entry.extension(self)
  File "D:\Applications\Anaconda3\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\reporter.py", line 90, in scope
    yield
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\training\trainer.py", line 289, in run
    update()
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\training\updater.py", line 170, in update
    self.update_core()
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\training\updater.py", line 182, in update_core
    optimizer.update(loss_func, *in_vars)
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\optimizer.py", line 408, in update
    self.call_hooks()
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\optimizer.py", line 243, in call_hooks
    hook(self)
  File "D:\Applications\Anaconda3\lib\site-packages\chainer\optimizer.py", line 493, in __call__
    'T p, T decay', 'T g', 'g += decay * p', 'weight_decay')
  File "cupy\util.pyx", line 30, in cupy.util.memoize.decorator.ret (cupy\util.cpp:1101)
  File "cupy\cuda\device.pyx", line 10, in cupy.cuda.device.get_device_id (cupy\cuda\device.cpp:999)
  File "cupy\cuda\runtime.pyx", line 156, in cupy.cuda.runtime.getDevice (cupy\cuda\runtime.cpp:2289)
  File "cupy\cuda\runtime.pyx", line 128, in cupy.cuda.runtime.check_status (cupy\cuda\runtime.cpp:1947)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorNoDevice: no CUDA-capable device is detected
```

**Comment by fquivira** [comment]
This issue is adressed by #1947
