### ISSUE TITLE
batch_matmul using GPU causes OverflowError when batch size == 1 on Windows

### ISSUE THREAD

**Issue by kamiyama-sat** [pfnet/chainer#1974]
Hi all.
batch_matmul causes OverflowError on my Chainer environment on Windows 64bit. 
My environment is as follows:
Chainer 1.18.0, Python 3.5.2 :: Anaconda custom (64-bit), CUDA 8.0.44, cuDNN 5.1.5, 
NVIDIA GeForce GTXTitan X, Windows 10 64bit (Build 14393)

Inputs

```
import numpy as np
from chainer import Variable
import chainer.functions as F
import cupy

x = Variable(cupy.zeros((1, 3, 3), dtype=np.float32))
y = F.batch_matmul(x, x, transb=True)
```

Outputs

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    y = F.batch_matmul(x, x, transb=True)
  File "C:\Anaconda3\lib\site-packages\chainer\functions\math\matmul.py", line 279, in batch_matmul
    return BatchMatMul(transa=transa, transb=transb)(a, b)
  File "C:\Anaconda3\lib\site-packages\chainer\function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "C:\Anaconda3\lib\site-packages\chainer\function.py", line 317, in forward
    return self.forward_gpu(inputs)
  File "C:\Anaconda3\lib\site-packages\chainer\functions\math\matmul.py", line 245, in forward_gpu
    a, b, transa=self.transa, transb=self.transb, out=ret)
  File "C:\Anaconda3\lib\site-packages\chainer\functions\math\matmul.py", line 84, in _batch_matmul_gpu
    ap = _mat_ptrs(a)
  File "C:\Anaconda3\lib\site-packages\chainer\functions\math\matmul.py", line 19, in _mat_ptrs
    return cuda.cupy.full((1,), a.data.ptr, dtype=numpy.uintp)
  File "C:\Anaconda3\lib\site-packages\cupy\creation\basic.py", line 188, in full
    a.fill(fill_value)
  File "cupy\core\core.pyx", line 343, in cupy.core.core.ndarray.fill (cupy\core\core.cpp:8532)
  File "cupy\core\core.pyx", line 355, in cupy.core.core.ndarray.fill (cupy\core\core.cpp:8478)
  File "cupy\core\core.pyx", line 1336, in cupy.core.core.elementwise_copy (cupy\core\core.cpp:52736)
  File "cupy\core\elementwise.pxi", line 731, in cupy.core.core.ufunc.__call__ (cupy\core\core.cpp:42384)
  File "cupy\core\elementwise.pxi", line 93, in cupy.core.core._preprocess_args (cupy\core\core.cpp:30420)
OverflowError: Python int too large to convert to C long
```

If I change batch size from 1 to 2, the test code runs without errors.

`x = Variable(cupy.zeros((2, 3, 3), dtype=np.float32))`

**Comment by kamiyama-sat** [comment]
This OverflowError on Windows was solved in Chainer 1.20.0. Thank you.
