### ISSUE TITLE
Need some advice setting up CUDA

### ISSUE THREAD

**Issue by juanmanavarro** [pfnet/chainer#2064]
Hi, I'm trying to set up CUDA but I've got this error:

```
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    cuda.get_device(args.gpu).use()
  File "/Library/Python/2.7/site-packages/chainer-1.19.0-py2.7.egg/chainer/cuda.py", line 178, in get_device
    check_cuda_available()
  File "/Library/Python/2.7/site-packages/chainer-1.19.0-py2.7.egg/chainer/cuda.py", line 83, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).CuPy is not correctly installed. 
Please check your environment, uninstall Chainer and reinstall it with `pip install chainer --no-cache-dir -vvvv`.
```

I have CuPy installed and I have followed the https://github.com/pfnet/chainer#installation, and of course, I uninstalled and installed chainer a thousand times. Any advice?

**Comment by unnonouno** [comment]
Which environment do you use? MacOS?
Please show me your whole install log  of `pip install chainer --no-cache-dir -vvvv`.
