### ISSUE TITLE
Error exmples for DCGAN

### ISSUE THREAD

**Issue by owruby** [pfnet/chainer#2120]
I' tried to run `python train_dcgan.py --gpu 0` and recieved this error.

``` python
Traceback (most recent call last):
  File "train_dcgan.py", line 115, in <module>
    main()
  File "train_dcgan.py", line 84, in main
    device=args.gpu)
  File "/home/s1311320/projects/practice/chainer-dev/examples/dcgan/updater.py", line 14, in __init__
    super(DCGANUpdater, self).__init__(*args, **kwargs)
  File "/home/s1311320/.pyenv/versions/chainer-dev/lib/python3.5/site-packages/chainer/training/updater.py", line 131, in __init__
    optimizer['main'].target.to_gpu(device)
KeyError: 'main'
```
I fixed `update.py`

from
``` python
if device is not None and device >= 0:
    optimizer['main'].target.to_gpu(device)
```

to
``` python
for opt in self._optimizers.values():
    opt.target.to_gpu(device)
```

**Comment by okuta** [comment]
This issue was fixed at #2121
