### ISSUE TITLE
snapshot failed when the model contains unused links with shape placeholder

### ISSUE THREAD

**Issue by mattya** [pfnet/chainer#2199]
For example, inserting
```hoge = L.Linear(None, 100),```
in https://github.com/pfnet/chainer/blob/master/examples/mnist/train_mnist.py#L17
cause following error at the snapshot timing.

```
Traceback (most recent call last):
  File "train_mnist.py", line 116, in <module>
    main()
  File "train_mnist.py", line 113, in main
    trainer.run()
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/training/trainer.py", line 298, in run
    entry.extension(self)
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/training/extensions/_snapshot.py", line 78, in snapshot
    _snapshot_object(trainer, trainer, filename.format(trainer), savefun)
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/training/extensions/_snapshot.py", line 88, in _snapshot_object
    savefun(tmppath, target)
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/serializers/npz.py", line 67, in save_npz
    s.save(obj)
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/serializer.py", line 69, in save
    obj.serialize(self)
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/training/trainer.py", line 310, in serialize
    self.updater.serialize(serializer['updater'])
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/training/updater.py", line 201, in serialize
    optimizer.target.serialize(serializer['model:' + name])
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/link.py", line 687, in serialize
    d[name].serialize(serializer[name])
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/link.py", line 687, in serialize
    d[name].serialize(serializer[name])
  File "/home/mattya/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer-1.20.0-py3.5-linux-x86_64.egg/chainer/link.py", line 488, in serialize
    self.add_param(name, initialized_value.shape)
AttributeError: 'NoneType' object has no attribute 'shape'

```

**Comment by gwtnb** [comment]
It seems that uninitialized parameters cannot be serialized. https://github.com/pfnet/chainer/blob/0587c39127f3bb0c8510d6f460e6d7a08cf7ba44/chainer/link.py#L485

But the error message should be clarified.
