### ISSUE TITLE
How to create dataset include variable size of images using chainer.datasets?

### ISSUE THREAD

**Issue by yizumi1012xxx** [pfnet/chainer#2230]
I want to treat variable size of images.
 (Images of width, height is variables, but channel is constant)

And, do not want to padding some values to solve shape mismatch

I try 'chainer.datases.LabeledImageDataset', but raise Error.
How to clear this problem chainer framework?

---
Traceback (most recent call last):
  File "/Users/xxx/Documents/workspace/cookpad/src/spp.py", line 106, in train_network
    trainer.run()
  File "/Users/xxx/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer/training/trainer.py", line 289, in run
    update()
  File "/Users/xxx/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer/training/updater.py", line 170, in update
    self.update_core()
  File "/Users/xxx/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer/training/updater.py", line 175, in update_core
    in_arrays = self.converter(batch, self.device)
  File "/Users/xxx/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer/dataset/convert.py", line 71, in concat_examples
    [example[i] for example in batch], padding[i])))
  File "/Users/xxx/.pyenv/versions/anaconda3-4.0.0/lib/python3.5/site-packages/chainer/dataset/convert.py", line 99, in _concat_arrays
    return xp.concatenate([array[None] for array in arrays])
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by unnonouno** [comment]
Yes, you can treat variable sizes of data using `converter` argument of Updater. The trainer framework of Chainer works like this:
- Dataset: It is a set of data, and it has the same interface of `list` such as `__getitem__`.
- Iterator: It extracts a subset from Dataset.
- Updater: It makes mini-batch data from a subset of data created by Iterator, and call optimizer to update mode parameters.

Updater has `converter` attribute which gets `batch` and `device`  argument and returns a tuple of ndarrays that is passed to the model. And you can change `converter` with `converter` argument of initializer of Updater. If you don't specify this argument, Updater uses `chainer.datset.cancat_examples` which concatenates a subset and makes a large ndarray.
I always make custom converter method to treat variable length inputs such as sentences in NLP field. This is an example: https://github.com/pfnet/chainer/pull/1375/files#diff-a39d90cc4e6178334a7d82c890dd6e80R67

See http://docs.chainer.org/en/stable/_modules/chainer/training/updater.html

**Comment by yizumi1012xxx** [comment]
Thank you for reply.

I solve this problem. So I close this issue.
