### ISSUE TITLE
Cupy function dose not work on Mac with GPU

### ISSUE THREAD

**Issue by takapoko** [pfnet/chainer#2290]
Dear Developers and users 

I have problem with cupy function in old MacBook Pro with GPU.
Import cupy and creating cupy.array is OK, but cannot call cupy.function through cuda library.

I had already repeated "pip install chainer --no-cache-dir -vvvv". But no error was written in the install logs.

Could you give me some advice?

Any idea will be appreciated

Best regards,

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
OS: Mac OSX Yosemite (10.10.5)
CPU: 2.4 GHz, Intel Core2Duo (MacBook Por 13inch, Mid 2010)
MEM: 4 GB
GPU: NVIDIA GeForce 320M 256MB
Python: python3.4 (osx-64) by Anaconda
Conda: anaconda3-2.3.0
Cuda : Cuda-6.5　※　Already confirmd installation by sample of asyncAPI
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

>>> import cupy
>>> x = cupy.array([1,2,3], cupy.float32)
>>> z = cupy.sum(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/cupy/math/sumprod.py", line 24, in sum
    return a.sum(axis, dtype, out, keepdims)
  File "cupy/core/core.pyx", line 798, in cupy.core.core.ndarray.sum (cupy/core/core.cpp:17586)
  File "cupy/core/core.pyx", line 806, in cupy.core.core.ndarray.sum (cupy/core/core.cpp:17456)
  File "cupy/core/reduction.pxi", line 263, in cupy.core.core.simple_reduction_function.__call__ (cupy/core/core.cpp:51937)
  File "cupy/cuda/function.pyx", line 130, in cupy.cuda.function.Function.linear_launch (cupy/cuda/function.cpp:3658)
  File "cupy/cuda/function.pyx", line 139, in cupy.cuda.function.Function.linear_launch (cupy/cuda/function.cpp:3505)
  File "cupy/cuda/function.pyx", line 107, in cupy.cuda.function._launch (cupy/cuda/function.cpp:2891)
  File "cupy/cuda/driver.pyx", line 127, in cupy.cuda.driver.launchKernel (cupy/cuda/driver.cpp:2540)
  File "cupy/cuda/driver.pyx", line 62, in cupy.cuda.driver.check_status (cupy/cuda/driver.cpp:1445)
cupy.cuda.driver.CUDADriverError: CUDA_ERROR_INVALID_VALUE: invalid argument
>>> 

$./train_mnist.py -g 0

Macintosh-3:chainer-sample macuser$ ./train_mnist.py -g 0
GPU: 0
 unit: 1000
 Minibatch-size: 100
 epoch: 20

Traceback (most recent call last):
  File "./train_mnist.py", line 115, in <module>
    main()
  File "./train_mnist.py", line 112, in main
    trainer.run()
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/training/trainer.py", line 295, in run
    update()
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/training/updater.py", line 174, in update
    self.update_core()
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/training/updater.py", line 186, in update_core
    optimizer.update(loss_func, *in_vars)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/optimizer.py", line 390, in update
    loss = lossfun(*args, **kwds)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/links/model/classifier.py", line 67, in __call__
    self.y = self.predictor(*x)
  File "./train_mnist.py", line 24, in __call__
    h1 = F.relu(self.l1(x))
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/links/connection/linear.py", line 91, in __call__
    self._initialize_params(x.size // x.shape[0])
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/links/connection/linear.py", line 77, in _initialize_params
    initializer=self._W_initializer)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/link.py", line 181, in add_param
    data = initializers.generate_array(initializer, shape, self.xp)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/initializers/__init__.py", line 46, in generate_array
    initializer(array)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/initializers/normal.py", line 94, in __call__
    Normal(s)(array)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/chainer/initializers/normal.py", line 31, in __call__
    loc=0.0, scale=self.scale, size=array.shape)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/cupy/random/distributions.py", line 90, in normal
    return (rs.normal(0, 1, size, dtype) * scale + loc).astype(dtype)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/cupy/random/generator.py", line 105, in normal
    return self._generate_normal(func, size, dtype, loc, scale)
  File "/Users/macuser/.pyenv/versions/anaconda3-2.3.0/lib/python3.4/site-packages/cupy/random/generator.py", line 68, in _generate_normal
    func(self._generator, out.data.ptr, out.size, *args)
  File "cupy/cuda/curand.pyx", line 171, in cupy.cuda.curand.generateNormalDouble (cupy/cuda/curand.cpp:3430)
  File "cupy/cuda/curand.pyx", line 179, in cupy.cuda.curand.generateNormalDouble (cupy/cuda/curand.cpp:3312)
  File "cupy/cuda/curand.pyx", line 85, in cupy.cuda.curand.check_status (cupy/cuda/curand.cpp:1437)
cupy.cuda.curand.CURANDError: CURAND_STATUS_DOUBLE_PRECISION_REQUIRED

**Comment by unnonouno** [comment]
I don't know this error message, but it looks that your GPU does not support double precision.

**Comment by unnonouno** [comment]
I fixed to avoid using double precision here: https://github.com/pfnet/chainer/tree/cupy-random-dtype
Please try it. If you can use it, i'll make pull request.

**Comment by takapoko** [comment]
Thank you! I will try it.

**Comment by unnonouno** [comment]
We merged this fix. Please check the latest stable version.

**Comment by niboshi** [comment]
I'm closing this issue. Please reopen if the problem persists.

**Comment by niboshi** [comment]
@Sangramsingkayte 
It seems your problem is not related to the original post.
I'd suggest opening a new issue.
(But before doing so, please check you have cupy installed.)
