### ISSUE TITLE
Broadcasting fails when using GPU version F.tile and F.sum

### ISSUE THREAD

**Issue by Signull8192** [pfnet/chainer#2392]
I found an unexpected error when using combination of F.tile and F.sum. This problem only occurs in GPU version. I confirmed this issue running with chainer 1.21.0, CUDA 7.5, cuDNN 5005.

Reproduction code:
```python
import numpy as np
from chainer import cuda, Variable
import chainer.functions as F

X = np.random.random((10, 2)).astype(np.float32)
Y = np.random.random((10, 2)).astype(np.float32)

x = Variable(X)
y = Variable(Y)
h = F.transpose(F.tile(F.sum(x, axis=1), (2, 1)))
loss = F.mean_squared_error(h, y)
loss.backward()
print "CPU test passed"

loss.unchain_backward()

X = np.random.random((10, 2)).astype(np.float32)
Y = np.random.random((10, 2)).astype(np.float32)

x = Variable(cuda.to_gpu(X))
y = Variable(cuda.to_gpu(Y))
h = F.transpose(F.tile(F.sum(x, axis=1), (2, 1)))
# h, y = F.broadcast(F.sum(x, axis=1)[:,np.newaxis], y)  # Equivalent code, this will work
loss = F.mean_squared_error(h, y)
loss.backward()  # Broadcasting error
print "GPU test passed"
```

Messages:
```
CPU test passed
Traceback (most recent call last):
  File "bug.py", line 33, in <module>
    loss.backward()  # Broadcasting error
  File "/home/kslab/yagi/.virtualenvs/lab/local/lib/python2.7/site-packages/chainer/variable.py", line 388, in backward
    gxs = func.backward(in_data, out_grad)
  File "/home/kslab/yagi/.virtualenvs/lab/local/lib/python2.7/site-packages/chainer/functions/math/sum.py", line 60, in backward
    gx[:] = gy
  File "cupy/core/core.pyx", line 1182, in cupy.core.core.ndarray.__setitem__ (cupy/core/core.cpp:25196)
  File "cupy/core/core.pyx", line 1760, in cupy.core.core.broadcast.__init__ (cupy/core/core.cpp:56168)
ValueError: Broadcasting failed
```

**Comment by unnonouno** [comment]
Thank you for reporting a bug and I found this is a bug of `cupy.tile`. I'll fix it.

**Comment by unnonouno** [comment]
Oh, I finally found that this is bug of `cupy.array`.
