### ISSUE TITLE
`import chainer` Fails

### ISSUE THREAD

**Issue by iwiwi** [pfnet/chainer#2544]
```(anaconda3-4.2.0) ~% python                                                                                                 [19:34:54]
Python 3.5.2 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:52:12)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import chainer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path-to-chainer>/__init__.py", line 13, in <module>
    from chainer import functions  # NOQA
  File "<path-to-chainer>/functions/__init__.py", line 40, in <module>
    from chainer.functions.array import spatial_transformer_sampler  # NOQA
  File "<path-to-chainer>/functions/array/spatial_transformer_sampler.py", line 12, in <module>
    _sampler_type = libcudnn.CUDNN_SAMPLER_BILINEAR
AttributeError: module 'cupy.cuda.cudnn' has no attribute 'CUDNN_SAMPLER_BILINEAR'
```

I installed GitHub master (`f21df12dbdefc613429e90ea6899e951daff3147`) with the following command: `python setup.py develop --cupy-no-cuda`.

**Comment by unnonouno** [comment]
It is defined in pxd file. Did you correctly rebuild after checkout? In some environment  you may need to remove all `.so` files and `build` directory.

**Comment by iwiwi** [comment]
Thank you, cleaning up and re-installation solved the problem. I'm sorry that I did not try that first.
