### ISSUE TITLE
Can not reinstall chainer, please help me

### ISSUE THREAD

**Issue by suishii** [pfnet/chainer#2734]
I install chainer and want to reinstall. When I reinstall ,it happen errors. My computer is Ubuntu 16 system, and in my computer I have two version python ,python2.7 and python3.5.
error:
Exception:
Traceback (most recent call last):
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/home/suiishii/.local/lib/python3.5/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/cupy'

**Comment by unnonouno** [comment]
It says, you don't have permission. Please use `sudo` or install chainer to your local environment with `--user` option: `pip install -U chainer --user`

**Comment by suishii** [comment]
It works. Thank you very much.
