### ISSUE TITLE
split_axis.backward fails on incomplete gradients

### ISSUE THREAD

**Issue by beam2d** [pfnet/chainer#308]
When there is a None in the grad_outputs, split_axis fails to backprop the incomplete gradients.

**Comment by nushio3** [comment]
minimum reproducing example:
```python
import chainer
from chainer import cuda
import chainer.functions as F
from chainer import optimizers
import numpy as np

xs = chainer.Variable(np.array([i for i in range(100)],dtype=np.float32))
_, smaller, _ = F.split_axis(xs, [24,47], axis=0)
smaller.backward()
```

result:
```
$ python split.py 
Traceback (most recent call last):
  File "split.py", line 11, in <module>
    smaller.backward()
  File "build/bdist.linux-x86_64/egg/chainer/variable.py", line 189, in backward
  File "build/bdist.linux-x86_64/egg/chainer/function.py", line 317, in backward
  File "build/bdist.linux-x86_64/egg/chainer/functions/split_axis.py", line 88, in backward_cpu
ValueError: zero-dimensional arrays cannot be concatenated
```
