### ISSUE TITLE
cudnn: bad param

### ISSUE THREAD

**Issue by ejlb** [pfnet/chainer#323]
Hello,

I'm trying to recreate the 16 layer VGG model in chainer. It works fine with cudnn disabled. If cudnn is enabled then I get the following error

```
Traceback (most recent call last):         
  File "./chainer-vggnet.py", line 162, in <module>
    loss, acc = model.forward(x_batch, y_batch)
  File "./chainer-vggnet.py", line 107, in forward
    h = F.relu(self.conv11(h))
  File "build/bdist.linux-x86_64/egg/chainer/function.py", line 166, in __call__
  File "build/bdist.linux-x86_64/egg/chainer/function.py", line 228, in forward
  File "build/bdist.linux-x86_64/egg/chainer/functions/convolution_2d.py", line 195, in forward_gpu
  File "build/bdist.linux-x86_64/egg/chainer/cudnn/libcudnn.py", line 1136, in cudnnGetConvolutionForwardWorkspaceSize
  File "build/bdist.linux-x86_64/egg/chainer/cudnn/libcudnn.py", line 290, in cudnnCheckStatus
chainer.cudnn.libcudnn.cudnnStatusBadParam
```

This is with chainer 1.1.2, cuda 7.0 and cudnn v3. The model looks like this

```
            conv1=F.Convolution2D(3, 64, 3, pad=1),
            conv2=F.Convolution2D(64, 64, 3, pad=1),

            conv3=F.Convolution2D(64, 128, 3, pad=1),
            conv4=F.Convolution2D(128, 128, 3, pad=1),

            conv5=F.Convolution2D(128, 256, 3, pad=1),
            conv6=F.Convolution2D(256, 256, 3, pad=1),
            conv7=F.Convolution2D(256, 256, 3, pad=1),

            conv8=F.Convolution2D(256, 512, 3, pad=1),
            conv9=F.Convolution2D(512, 512, 3, pad=1),
            conv10=F.Convolution2D(512, 512, 3, pad=1),

            conv11=F.Convolution2D(512, 512, 3, pad=1),
            conv12=F.Convolution2D(512, 512, 3, pad=1),
            conv13=F.Convolution2D(512, 512, 3, pad=1),

            fc1=F.Linear(512, 512),
            fc2=F.Linear(512, 10)
```

Thanks

**Comment by ejlb** [comment]
oops, my mistake :)

**Comment by JakeRyan1** [comment]
What was the solution?
