### ISSUE TITLE
cupy.cudnn.reset_handles() fails for atexit run time

### ISSUE THREAD

**Issue by kikusu** [pfnet/chainer#339]
- chainer (fc79c3caf0a5ebea1bcbb1570b48c057577cf1ad) with GPU
- cuDNN not installed
- python (using pyenv)

```
Python 2.7.10 (default, Jun 19 2015, 20:41:53)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import chainer
>>> exit()
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "****/2.7.10/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "cupy/cudnn.py", line 35, in reset_handles
    for handle in six.itervalues(handles):
AttributeError: 'NoneType' object has no attribute 'itervalues'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "***/2.7.10/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "cupy/cudnn.py", line 35, in reset_handles
    for handle in six.itervalues(handles):
AttributeError: 'NoneType' object has no attribute 'itervalues'
```

I can see the problem as follows
1. cupy/cudnn.py:10 `from cupy.cuda import cudnn` fails because cuDNN is not installed.
2. However, `import cupy.cudnn` fails because `cudnn` is used in cupy/cudnn.py (name 'cudnn' is not defined)
3. The handling of the global variable(`cupy.cudnn._handles`) of this time seems to be different from python3.3~ in python2.

test_code.py
```
import atexit

global_variable = []

@atexit.register
def exit_func():
    global global_variable
    print("global_variable is ", global_variable)


fail_code # this is fail code
```

python 2.7.10
```
Python 2.7.10 (default, Jun 19 2015, 20:41:53)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_code
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test_code.py", line 11, in <module>
    fail_code # this is fail code
NameError: name 'fail_code' is not defined
>>> exit()
('global_variable is ', None)
```

python 3.4.3
```
Python 3.4.3 (default, Aug 13 2015, 16:03:08)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import test_code
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test_code.py", line 11, in <module>
    fail_code # this is fail code
NameError: name 'fail_code' is not defined
>>> exit()
global_variable is  []
```
The result is `[]` in the python3.3.x~, but becomes `None` in python2.
But python3.0.1, 3.1.5, 3.2.6 result is 'None', python 2.7.0 is [].

**Comment by beam2d** [comment]
Thank you for the detailed report! I notice that I mistook to handle the availability of cuDNN. `cupy.cudnn` should not be importable if cuDNN is not available. I'll fix it.
