### ISSUE TITLE
AttributeError: 'GPUArray' object has no attribute 'argmax'

### ISSUE THREAD

**Issue by andyyuan78** [pfnet/chainer#41]
ubgpu@ubgpu:~/github/chainer$ python examples/sentiment/train_sentiment.py --gpu=0
Epoch: 0
loss: 270866.15
11.64 iters/sec, 734.28 sec

Epoch: 1
loss: 232619.31
10.74 iters/sec, 795.38 sec

Epoch: 2
loss: 218530.70
10.43 iters/sec, 819.13 sec

Epoch: 3
loss: 208379.96
10.66 iters/sec, 801.55 sec

Epoch: 4
loss: 199109.27
10.76 iters/sec, 793.75 sec

Train data evaluation:
Traceback (most recent call last):
  File "examples/sentiment/train_sentiment.py", line 185, in <module>
    evaluate(train_trees)
  File "examples/sentiment/train_sentiment.py", line 124, in evaluate
    traverse(tree, train=False, evaluate=result)
  File "examples/sentiment/train_sentiment.py", line 93, in traverse
    left_loss, left = traverse(left_node, train=train, evaluate=evaluate, root=False)
  File "examples/sentiment/train_sentiment.py", line 93, in traverse
    left_loss, left = traverse(left_node, train=train, evaluate=evaluate, root=False)
  File "examples/sentiment/train_sentiment.py", line 93, in traverse
    left_loss, left = traverse(left_node, train=train, evaluate=evaluate, root=False)
  File "examples/sentiment/train_sentiment.py", line 93, in traverse
    left_loss, left = traverse(left_node, train=train, evaluate=evaluate, root=False)
  File "examples/sentiment/train_sentiment.py", line 108, in traverse
    predict = y.data.argmax(1)
AttributeError: 'GPUArray' object has no attribute 'argmax'
ubgpu@ubgpu:~/github/chainer$

**Comment by unnonouno** [comment]
Sorry, it is a known bug, and is fixed in the master branch. Wait the next version or use the master branch.
See this patch: https://github.com/pfnet/chainer/pull/30
