### ISSUE TITLE
cupy.random.randn raises an error when generating an array with an odd number of elements

### ISSUE THREAD

**Issue by rharang** [pfnet/chainer#422]
For example:
```
>>> from chainer import cuda
>>> cuda.cupy.random.randn(1,2)
array([[-0.25047453,  0.7825017 ]])
>>> cuda.cupy.random.randn(1,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../chainer-1.3.0-py2.7.egg/cupy/random/sample.py", line 52, in randn
    return distributions.normal(size=size, dtype=dtype)
  File .../chainer-1.3.0-py2.7.egg/cupy/random/distributions.py", line 47, in normal
    return rs.normal(loc, scale, size=size, dtype=dtype)
  File ".../chainer-1.3.0-py2.7.egg/cupy/random/generator.py", line 89, in normal
    func(self._generator, out.data.ptr, out.size, loc, scale)
  File ".../chainer-1.3.0-py2.7.egg/cupy/cuda/curand.py", line 196, in generateNormalDouble
    check_status(status)
  File ".../chainer-1.3.0-py2.7.egg/cupy/cuda/curand.py", line 79, in check_status
    raise CURANDError(status)
cupy.cuda.curand.CURANDError: CURAND_STATUS_LENGTH_NOT_MULTIPLE
>>> cuda.cupy.random.randn(1,4)
array([[-2.93901085, -0.69427899,  0.18251298,  1.91443934]])
>>> cuda.cupy.random.randn(2,2)
array([[-1.75610197,  0.79795696],
       [-1.04317749, -0.50339785]])
>>> cuda.cupy.random.randn(3,3)
[Snip identical error output]
```
I've done a search over a range of different shapes, and the one constant seems to be that an odd number of elements reliably results in the above error.

**Comment by unnonouno** [comment]
Yes, we know this problem in #390. It is because curand library in CUDA doesn't support odd number of elements. We need to make a wrapper method for this problem.

**Comment by unnonouno** [comment]
I noticed that `curandGenerateLogNormal` and `curandGenerateLogNormalDouble` also  have the same problem.
http://docs.nvidia.com/cuda/curand/group__HOST.html
