### ISSUE TITLE
`divmod` doesn't work for `cupy.ndarray`

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#434]
```
>>> u=cupy.array(1)
>>> divmod(u, 3)
/tmp/tmpDpvsv8/kern.cu(273): error: identifier "out1" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00003ba3_00000000-6_kern.cpp1.ii".
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/__init__.py", line 752, in __divmod__
    return elementwise._divmod(self, other)
  File "cupy/elementwise.py", line 637, in __call__
    self._params, self.name, self._preamble)
  File "cupy/util.py", line 34, in ret
    result = f(*args, **kwargs)
  File "cupy/elementwise.py", line 479, in _get_ufunc_kernel
    kernel_params, operation, name, preamble)
  File "cupy/elementwise.py", line 36, in _get_simple_elementwise_kernel
    module = carray.compile_with_cache(module_code, options)
  File "cupy/carray.py", line 74, in compile_with_cache
    return cuda.compile_with_cache(source, options, arch, cachd_dir)
  File "cupy/cuda/compiler.py", line 125, in compile_with_cache
    cubin = nvcc(source, options, arch)
  File "cupy/cuda/compiler.py", line 50, in nvcc
    subprocess.check_output(cmd, cwd=root_dir)
  File "/home/unno/.pyenv/versions/2.7.8/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['nvcc', '--cubin', '-arch', 'sm_52', '/tmp/tmpDpvsv8/kern.cu']' returned non-zero exit status 2
```

**Comment by delta2323** [comment]
Could you tell me the detail of `u` in the code?

**Comment by unnonouno** [comment]
I fixed code snippet.
