### ISSUE TITLE
cuda import error

### ISSUE THREAD

**Issue by jramapuram** [pfnet/chainer#571]
This just started happening recently.

Everything was working, however I seem to be getting this across different machines with CUDA setup and installed correctly to `/usr/local/cuda`

I have already tried:
  - reinstall chainer
  - remove pycuda, chainer-deps, etc & reinstall
  - my six install is latest

```bash
 $ python chainer.py
Traceback (most recent call last):
  File "chainer.py", line 17, in <module>
    import chainer
  File "/home/ubuntu/chainer.py", line 18, in <module>
    from chainer import cuda
ImportError: cannot import name cuda
```

**Comment by jramapuram** [comment]
Gah I believe this was due to the file being named `chainer.py`, sorry.
