### ISSUE TITLE
caffe models from zoo import error

### ISSUE THREAD

**Issue by Strateus** [pfnet/chainer#651]
Tried to import 2 caffe models, both raise same error:

```
>>> from chainer.functions.caffe import CaffeFunction
>>> func = CaffeFunction('/root/models/vgg_face_caffe/VGG_FACE.caffemodel')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/caffe/caffe_function.py", line 119, in __init__
    meth(self, layer)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/caffe/caffe_function.py", line 232, in _setup_convolution
    func.W.fill(0)
AttributeError: 'Variable' object has no attribute 'fill'
>>> func = CaffeFunction('/root/models/nin/nin_imagenet.caffemodel')       
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/caffe/caffe_function.py", line 128, in __init__
    meth(self, layer)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/caffe/caffe_function.py", line 232, in _setup_convolution
    func.W.fill(0)
AttributeError: 'Variable' object has no attribute 'fill'
>>> 
```

What i am doing wrong? Or it is some bug?

**Comment by unnonouno** [comment]
Sorry, this is a bug appeared in the last week. I'll fix it. And thank you for reporting a bug.

**Comment by Strateus** [comment]
Thank you, it works now!
Can you please tell why softmax layer cannot be imported? Anything to read about this decision (that you do not import last layers, with no top connections)?
