### ISSUE TITLE
Chainer Connection to GPU Issue on Mac

### ISSUE THREAD

**Issue by mshahriarinia** [pfnet/chainer#652]
Here is Chainer version:
```
$ pip freeze | grep chainer
chainer==1.4.1
```
It can not connect to GPU while I have used cuda and gpu for theano before.
```
>>> import chainer
>>> from chainer import cuda
>>> cuda.cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'cupy'
```

**Comment by delta2323** [comment]
Could you try to import cupy directly by `import cupy`? I expect this raises error. If it does raise, would you let me know the error message?

**Comment by mshahriarinia** [comment]
```
>>> import cuda
Traceback (most recent call last):
File "", line 1, in 
ImportError: No module named cuda
```

**Comment by delta2323** [comment]
Sorry for confusing you. Please import cupy, not cuda.

**Comment by mshahriarinia** [comment]
Oh! My bad. importing cupy was O.K.
```
>>> import cupy
>>>
```

**Comment by delta2323** [comment]
Hum... Then could you do the following command?
```
from chainer import cuda
cuda.check_cuda_available()
```

**Comment by mshahriarinia** [comment]
```
>>> from chainer import cuda
>>> cuda.check_cuda_available()
>>>
```

**Comment by mshahriarinia** [comment]
The error seems to have been fixed. One of our colleagues recently updated chainer to its latest version and I don't see the error any more. Thanks for your support!

**Comment by mshahriarinia** [comment]
Sorry this is still valid on other machine. Below you can see the sections we discussed above 

```
$ python
Enthought Canopy Python 2.7.9 | 64-bit | (default, Jun 30 2015, 19:41:21)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import chainer
>>> from chainer import cuda
>>> cuda.cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'cupy'
>>> import cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/__init__.py", line 9, in <module>
    from cupy import binary
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/binary/__init__.py", line 5, in <module>
    from cupy.binary import elementwise  # NOQA
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/binary/elementwise.py", line 1, in <module>
    from cupy import elementwise
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/elementwise.py", line 7, in <module>
    from cupy import carray
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/carray.py", line 6, in <module>
    from cupy import cuda
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/cuda/__init__.py", line 1, in <module>
    from cupy.cuda import compiler
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/cuda/compiler.py", line 12, in <module>
    from cupy.cuda import device
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/cuda/device.py", line 5, in <module>
    from cupy.cuda import cublas
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/cuda/cublas.py", line 5, in <module>
    from cupy.cuda import driver
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/cupy/cuda/driver.py", line 17, in <module>
    from cupy.cuda import internal
ImportError: cannot import name internal
>>> from chainer import cuda
>>> cuda.check_cuda_available()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/morteza/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/chainer-1.4.1-py2.7.egg/chainer/cuda.py", line 82, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up.
library not found. ['libcuda.dylib']
>>>
```

**Comment by delta2323** [comment]
Thank you for sharing the error message. It seems Chainer cannot find `libcuda.dylib`. Please add the directory where this library is installed to `LD_LIBRARY_PATH` and check if it works.

**Comment by mshahriarinia** [comment]
`export LD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:/usr/local/cuda/lib/:$LD_LIBRARY_PATH` solved the problem. Thank you very much.

**Comment by Sangramsingkayte** [comment]
Command "/Users/sangramsing/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/2s/t87spp4d2mldhm8gbnj7xfs40000gn/T/pip-install-daro7gk6/cupy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/2s/t87spp4d2mldhm8gbnj7xfs40000gn/T/pip-record-1r19bz51/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2s/t87spp4d2mldhm8gbnj7xfs40000gn/T/pip-install-daro7gk6/cupy/
