### ISSUE TITLE
caffe model raises AttritbureError on GPU

### ISSUE THREAD

**Issue by Strateus** [pfnet/chainer#656]
Something is wrong with GPU computation on Caffe model, for CPU it works with last fix, please check it:

```
>>> func.to_cpu()
<chainer.links.caffe.caffe_function.CaffeFunction object at 0x7f35c3003090>
>>> y, = func(inputs={'data': x}, outputs=['fc8'])
>>> y.data.shape
(1, 2622)
>>> func.to_gpu(0)
<chainer.links.caffe.caffe_function.CaffeFunction object at 0x7f35c3003090>
>>> y, = func(inputs={'data': x}, outputs=['fc8'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/links/caffe/caffe_function.py", line 170, in __call__
    output_vars = func(*input_vars)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/links/connection/convolution_2d.py", line 75, in __call__
    x, self.W, self.b, *self._conv_arg)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/connection/convolution_2d.py", line 267, in convolution_2d
    return func(x, W, b)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/function.py", line 105, in __call__
    outputs = self.forward(in_data)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/function.py", line 181, in forward
    return self.forward_gpu(inputs)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/connection/convolution_2d.py", line 100, in forward_gpu
    handle, one.data, x_desc.value, x.data.ptr,
AttributeError: 'buffer' object has no attribute 'ptr'
>>> 
```

I have Cuda 7.5 with cudnn 3 installed

**Comment by unnonouno** [comment]
Can you check type of `x.data`? I think `x.data` is not `cupy.ndarray` but `numpy.ndarray`.

**Comment by Strateus** [comment]
yep, thank you
