### ISSUE TITLE
Cudnn create_tensor_descriptor error

### ISSUE THREAD

**Issue by Strateus** [pfnet/chainer#670]
Assigned F.average_pooling_2d(h, 7) layer, shape of h before Exception is (16, 1024, 2, 2)

```
root@gpu:~/triplet_chainer# python train_test.py --gpu 0 --batchsize 16 --optimizer Adadelta
(16, 576, 3, 3)
(16, 1024, 2, 2)
(16, 1024, 2, 2)
(16, 1024, 2, 2)
Traceback (most recent call last):
  File "train_test.py", line 285, in <module>
    model = train(args, train_data, train_label, model, optimizer)
  File "train_test.py", line 207, in train
    mean_loss = train_epoch(X_tr, y_tr, xp, args, optimizer, model)
  File "train_test.py", line 137, in train_epoch
    triplets = sample_triplets(xp.asarray(X, dtype=xp.float32), y, xp, model)
  File "train_test.py", line 61, in sample_triplets
    embeddings = model.forward_once(X, train=False)
  File "/root/triplet_chainer/TripletNetwork.py", line 63, in forward_once
    h = F.average_pooling_2d(h, 7)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/pooling/average_pooling_2d.py", line 138, in average_pooling_2d
    return AveragePooling2D(ksize, stride, pad, False, use_cudnn)(x)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/function.py", line 105, in __call__
    outputs = self.forward(in_data)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/function.py", line 181, in forward
    return self.forward_gpu(inputs)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/pooling/average_pooling_2d.py", line 25, in forward_gpu
    return super(AveragePooling2D, self).forward_gpu(x)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/chainer/functions/pooling/pooling_2d.py", line 56, in forward_gpu
    y_desc = cudnn.create_tensor_descriptor(y)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.4.1-py2.7-linux-x86_64.egg/cupy/cudnn.py", line 67, in create_tensor_descriptor
    *arr.shape)
  File "cupy/cuda/cudnn.pyx", line 206, in cupy.cuda.cudnn.setTensor4dDescriptor (/root/chainer/cupy/cuda/cudnn.cpp:2170)
  File "cupy/cuda/cudnn.pyx", line 211, in cupy.cuda.cudnn.setTensor4dDescriptor (/root/chainer/cupy/cuda/cudnn.cpp:2030)
  File "cupy/cuda/cudnn.pyx", line 164, in cupy.cuda.cudnn.check_status (/root/chainer/cupy/cuda/cudnn.cpp:1308)
cupy.cuda.cudnn.CuDNNError: CUDNN_STATUS_BAD_PARAM: CUDNN_STATUS_BAD_PARAM
```

Is it a known bug or im doing something wrong?

**Comment by unnonouno** [comment]
It looks a bug. Please teach me `h.shape` here:
```
  File "/root/triplet_chainer/TripletNetwork.py", line 63, in forward_once
    h = F.average_pooling_2d(h, 7)
```

**Comment by Strateus** [comment]
It did not happen again, im not sure why, maybe it was my mistake, i will report again if it happens.

**Comment by beam2d** [comment]
Close. Please let us know if this happens again!
