### ISSUE TITLE
ImportError when installing chainer 1.5 via pip

### ISSUE THREAD

**Issue by rezoo** [pfnet/chainer#679]
When I tried to install chainer v1.5 via PyPI, I got the ImportError:
```
$ pip install chainer
Collecting chainer
  Using cached chainer-1.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-CB4n6T/chainer/setup.py", line 7, in <module>
        import chainer_setup_build
    ImportError: No module named chainer_setup_build

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CB4n6T/chainer
```
Do you have got any advice?

**Comment by wkentaro** [comment]
Maybe need [MANIFEST.in] when releasing chainer? https://docs.python.org/2/distutils/sourcedist.html#the-manifest-in-template

**Comment by wkentaro** [comment]
like 
```
# MANIFEST.in
include chainer_setup_build.py
```

**Comment by wkentaro** [comment]
@rezoo fixed? On my pc, it works.

**Comment by rezoo** [comment]
Thanks! In version 1.5.0.2 it might work well.
