### ISSUE TITLE
Mnist example OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Strateus** [pfnet/chainer#698]
Im not sure what files are missing? It seems like Chainer cannot compile Cuda kernel?

```
root@igor-GS60-2QD:~/chainer# ./examples/mnist/train_mnist.py -g 0
load MNIST dataset
Downloading train-images-idx3-ubyte.gz...
Done
Downloading train-labels-idx1-ubyte.gz...
Done
Downloading t10k-images-idx3-ubyte.gz...
Done
Downloading t10k-labels-idx1-ubyte.gz...
Done
Converting training data...
Done
Converting test data...
Done
Save output...
Done
Convert completed
epoch 1
Traceback (most recent call last):
  File "./examples/mnist/train_mnist.py", line 88, in <module>
    optimizer.update(model, x, t)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.5.0.2-py2.7-linux-x86_64.egg/chainer/optimizer.py", line 376, in update
    self.target.zerograds()
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.5.0.2-py2.7-linux-x86_64.egg/chainer/link.py", line 530, in zerograds
    super(Chain, self).zerograds()
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.5.0.2-py2.7-linux-x86_64.egg/chainer/link.py", line 318, in zerograds
    param.zerograd()
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.5.0.2-py2.7-linux-x86_64.egg/chainer/variable.py", line 151, in zerograd
    self._grad.fill(0)
  File "cupy/core/core.pyx", line 364, in cupy.core.core.ndarray.fill (cupy/core/core.cpp:7870)
    cpdef fill(self, value):
  File "cupy/core/core.pyx", line 373, in cupy.core.core.ndarray.fill (cupy/core/core.cpp:7815)
    elementwise_copy(value, self, dtype=self.dtype)
  File "cupy/core/elementwise.pxi", line 756, in cupy.core.core.ufunc.__call__ (cupy/core/core.cpp:42043)
    kern = _get_ufunc_kernel(
  File "cupy/util.pyx", line 36, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1194)
    result = f(*args, **kwargs)
  File "cupy/core/elementwise.pxi", line 566, in cupy.core.core._get_ufunc_kernel (cupy/core/core.cpp:38632)
    return _get_simple_elementwise_kernel(
  File "cupy/core/elementwise.pxi", line 32, in cupy.core.core._get_simple_elementwise_kernel (cupy/core/core.cpp:29309)
    module = compile_with_cache(module_code, options)
  File "cupy/core/carray.pxi", line 87, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:28987)
    return cuda.compile_with_cache(source, options, arch, cachd_dir)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.5.0.2-py2.7-linux-x86_64.egg/cupy/cuda/compiler.py", line 102, in compile_with_cache
    base = _empty_file_preprocess_cache[env] = preprocess('', options)
  File "/root/anaconda2/lib/python2.7/site-packages/chainer-1.5.0.2-py2.7-linux-x86_64.egg/cupy/cuda/compiler.py", line 65, in preprocess
    pp_src = subprocess.check_output(cmd, cwd=root_dir)
  File "/root/anaconda2/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/root/anaconda2/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/root/anaconda2/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by unnonouno** [comment]
Is `nvcc` command is in your `PATH` environment variable? Please check it with `which nvcc`.

**Comment by Strateus** [comment]
Thank you, adding export of PATH with /usr/local/cuda-7.5/bin to .bashrc file helped!
