### ISSUE TITLE
examples/mnist failed when GPU option given

### ISSUE THREAD

**Issue by uetchy** [pfnet/chainer#780]
I'm getting into [chainer/examples/mnist](https://github.com/pfnet/chainer/tree/master/examples/mnist) and facing following error:

```console
$ python train_mnist.py -g 0
load MNIST dataset
Traceback (most recent call last):
  File "train_mnist.py", line 54, in <module>
    cuda.get_device(args.gpu).use()
  File "/Users/uetchy/.pyenv/versions/3.5.1/lib/python3.5/site-packages/chainer/cuda.py", line 159, in get_device
    check_cuda_available()
  File "/Users/uetchy/.pyenv/versions/3.5.1/lib/python3.5/site-packages/chainer/cuda.py", line 82, in check_cuda_available
    raise RuntimeError(msg)
RuntimeError: CUDA environment is not correctly set up
(see https://github.com/pfnet/chainer#installation).dlopen(/Users/uetchy/.pyenv/versions/3.5.1/lib/python3.5/site-packages/cupy/core/core.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libcublas.7.5.dylib
  Referenced from: /Users/uetchy/.pyenv/versions/3.5.1/lib/python3.5/site-packages/cupy/core/core.cpython-35m-darwin.so
  Reason: image not found
```

I've put CUDA 7.5 and its env path into precise location.
What I do to fix this issue?

This is my environment:
```console
$ uname -a # OSX El Capitan
Darwin 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

$ python --version
Python 3.5.1

$ pip freeze
appnope==0.1.0
chainer==1.5.1
click==6.2
cycler==0.9.0
Cython==0.23.4
decorator==4.0.6
filelock==2.0.5
first==2.0.1
gnureadline==6.3.3
h5py==2.5.0
ipykernel==4.2.1
ipython==4.0.1
ipython-genutils==0.1.0
ipywidgets==4.1.1
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
MarkupSafe==0.23
matplotlib==1.5.0
mistune==0.7.1
nbconvert==4.1.0
nbformat==4.0.1
nose==1.3.7
notebook==4.0.6
numpy==1.10.2
path.py==8.1.2
pexpect==4.0.1
pickleshare==0.5
pip-tools==1.4.2
protobuf==2.6.1
ptyprocess==0.5
Pygments==2.0.2
pyparsing==2.0.6
python-dateutil==2.4.2
pytz==2015.7
pyzmq==15.1.0
scipy==0.16.1

$ echo $PATH
/usr/local/cuda/bin:/Users/uetchy/.pyenv/shims:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/local/lib/node_modules

$ echo $LD_LIBRARY_PATH
/usr/local/cuda/lib

$ ls /usr/local/cuda/bin
bin2c                       cudafe++                    nvlink
computeprof                 cuobjdump                   nvprof
crt                         fatbinary                   nvprune
cuda-binary-gdb             filehash                    nvvp
cuda-gdb                    nsight                      ptxas
cuda-install-samples-7.5.sh nvcc                        uninstall_cuda_7.5.pl
cuda-memcheck               nvcc.profile
cudafe                      nvdisasm

$ ls /usr/local/cuda/lib
libcublas.7.5.dylib         libcuinj.7.5.dylib          libnppi.7.5.dylib
libcublas.dylib             libcuinj.dylib              libnppi.dylib
libcublas_device.a          libculibos.a                libnppi_static.a
libcublas_static.a          libcurand.7.5.dylib         libnpps.7.5.dylib
libcuda.dylib               libcurand.dylib             libnpps.dylib
libcudadevrt.a              libcurand_static.a          libnpps_static.a
libcudart.7.5.dylib         libcusolver.7.5.dylib       libnvToolsExt.1.dylib
libcudart.dylib             libcusolver.dylib           libnvToolsExt.dylib
libcudart_static.a          libcusolver_static.a        libnvblas.7.5.dylib
libcufft.7.5.dylib          libcusparse.7.5.dylib       libnvblas.dylib
libcufft.dylib              libcusparse.dylib           libnvrtc-builtins.7.5.dylib
libcufft_static.a           libcusparse_static.a        libnvrtc-builtins.dylib
libcufftw.7.5.dylib         libnppc.7.5.dylib           libnvrtc.7.5.dylib
libcufftw.dylib             libnppc.dylib               libnvrtc.dylib
libcufftw_static.a          libnppc_static.a            stubs
```

And there are what I did.
```console
$ pyenv install 3.5.1
$ pyenv global 3.5.1
$ pip install -U setuptools
$ CUDA_PATH=/usr/local/cuda pip install chainer --no-cache
```

**Comment by unnonouno** [comment]
Humm, your process looks good.
Did you try to use `DYLD_LIBRARY_PATH`?

```
export DYLD_LIBRARY_PATH=/usr/local/cuda
```

**Comment by uetchy** [comment]
Yes. I did tried `DYLD_LIBRARY_PATH` but it changed nothing.
I think this is OS X specific problem. Because TensorFlow, another similar library, also provides GPU mode only for Ubuntu.

**Comment by unnonouno** [comment]
I tried to install chainer with cuda to my mac without nvidia GPUs. And, i got the same error.

```
$ unset DYLD_LIBRARY_PATH
$ pip install chainer
$ python
...
>>> import cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/unno/.pyenv/versions/2.7.8/lib/python2.7/site-packages/cupy/__init__.py", line 8, in <module>
    from cupy import binary
  File "/Users/unno/.pyenv/versions/2.7.8/lib/python2.7/site-packages/cupy/binary/__init__.py", line 5, in <module>
    from cupy.binary import elementwise  # NOQA
  File "/Users/unno/.pyenv/versions/2.7.8/lib/python2.7/site-packages/cupy/binary/elementwise.py", line 1, in <module>
    from cupy import core
  File "/Users/unno/.pyenv/versions/2.7.8/lib/python2.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core
ImportError: dlopen(/Users/unno/.pyenv/versions/2.7.8/lib/python2.7/site-packages/cupy/core/core.so, 2): Library not loaded: @rpath/libcublas.7.5.dylib
  Referenced from: /Users/unno/.pyenv/versions/2.7.8/lib/python2.7/site-packages/cupy/core/core.so
  Reason: image not found
```

And then, I set `DYLD_LIBRARY_PATH` and import cupy. I got no error.
```
$ export DYLD_LIBRARY_PATH=/usr/local/cuda/lib  # sorry i mistook the path
$ python
...
>>> import cupy
>>>
```

**Comment by uetchy** [comment]
@unnonouno It's still failing. I'm curious about your cuDNN version. My version is 4.

**Comment by unnonouno** [comment]
I'm using cuDNN v3. cuDNN v4 is not supported yet. But, `libcublas` is in CUDA.

**Comment by unnonouno** [comment]
I'm suspecting El capitan. This comment looks like the problem:
https://github.com/dmlc/mxnet/issues/575#issuecomment-158629933

**Comment by uetchy** [comment]
Hooray! Disabling SIP is just what I need.

In conclution, this is how to install chainer on OS X El Capitan:

1. Disable SIP by `csrutil disable` command in rescue mode
2. Install __CUDA Toolkit 7.5__ and __cuDNN v3__
3. Put ENV vars
```
CPATH=/opt/cudnn/include
LIBRARY_PATH=/opt/cudnn/lib
DYLD_LIBRARY_PATH=/usr/local/cuda/lib:/opt/cudnn/lib
```
4. `pip install chainer`

Thank you for investigating this issue. 

This knowledge should be described on README for all OS X El Capitan users.

**Comment by kcarnold** [comment]
Using DYLD_LIBRARY_PATH, and disabling SIP to make it work, should be an option of last resort. Libraries should be built with the correct rpath. Unfortunately the build chain doesn't Do The Right Thing by default, causing pain over and over again. See my PR #1153 for an admittedly kinda hacky solution.

**Comment by unnonouno** [comment]
Oh, great! Thank you for PR. I'll try it.
