### ISSUE TITLE
`int` argument for `take` doesn't work

### ISSUE THREAD

**Issue by unnonouno** [pfnet/chainer#861]
```
>>> numpy.arange(10).take(1)
1
>>> cupy.arange(10).take(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/core/core.pyx", line 552, in cupy.core.core.ndarray.take (cupy/core/core.cpp:10310)
    cpdef ndarray take(self, indices, axis=None, out=None):
  File "cupy/core/core.pyx", line 560, in cupy.core.core.ndarray.take (cupy/core/core.cpp:10193)
    return _take(self, indices, axis, out)
  File "cupy/core/core.pyx", line 1683, in cupy.core.core._take (cupy/core/core.cpp:52483)
    a = rollaxis(a, axis)
TypeError: 'NoneType' object cannot be interpreted as an index
```

**Comment by unnonouno** [comment]
related to #852
