### ISSUE TITLE
Install was failed with Windows and MInGW

### ISSUE THREAD

**Issue by fx-kirin** [pfnet/chainer#975]
Hi. Thanks for the great project.  I'm a newbie to chainer and github. I got errors when I installed it, so I'd like to leave a feedback.

`python setup.py install` was failed because of the method `distutils.sysconfig.customize_compiler(compiler)` in the line 235 of 'chainer_setup_build.py'.

The method tried to add unix environment parameters (like 'CC' or 'AR') to the `compiler` object.

When I commented out the line, chainer was successfully installed.

Whole error is the following.

    running install
    running bdist_egg
    running egg_info
    writing requirements to chainer.egg-info\requires.txt
    writing chainer.egg-info\PKG-INFO
    writing top-level names to chainer.egg-info\top_level.txt
    writing dependency_links to chainer.egg-info\dependency_links.txt
    Executing cythonize
    Options: {'profile': False, 'annotate': False, 'linetrace': False, 'no_cuda': Fa
    lse}
    Traceback (most recent call last):
      File "setup.py", line 90, in <module>
        'build_ext': chainer_setup_build.chainer_build_ext,
      File "C:\Python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 67, i
    n run
        self.do_egg_install()
      File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 109,
    in do_egg_install
        self.run_command('bdist_egg')
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 152
    , in run
        self.run_command("egg_info")
      File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 186,
     in run
        self.find_sources()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 209,
     in find_sources
        mm.run()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 293,
     in run
        self.add_defaults()
      File "C:\Python27\lib\site-packages\setuptools\command\egg_info.py", line 322,
     in add_defaults
        sdist.add_defaults(self)
      File "C:\Python27\lib\site-packages\setuptools\command\sdist.py", line 132, in
     add_defaults
        build_ext = self.get_finalized_command('build_ext')
      File "C:\Python27\lib\distutils\cmd.py", line 312, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "C:\Python27\lib\distutils\cmd.py", line 109, in ensure_finalized
        self.finalize_options()
      File "C:\Users\Zenbook\Downloads\chainer-master\chainer-master\chainer_setup_b
    uild.py", line 435, in finalize_options
        distutils.sysconfig.customize_compiler(compiler)
      File "C:\Python27\lib\distutils\sysconfig.py", line 195, in customize_compiler

        cpp = cc + " -E"           # not always
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Comment by arita37** [comment]
Hi,

I got the same issue.

There is some explanation here:
http://qiita.com/icoxfog417/items/ca1521f9d62183cea234

but, clean installation is not explained.
anybody can help ?
