### ISSUE TITLE
1.7.0 debug mode bug

### ISSUE THREAD

**Issue by ejlb** [pfnet/chainer#999]
Hi,

I tested the debug model on one of my existing models and got:

```
Traceback (most recent call last):
  File "./train.py", line 53, in <module>
    loss.backward()
  File "/home/eddie/envs/deep/local/lib/python2.7/site-packages/chainer/variable.py", line 355, in backward
    for gx in gxs):
  File "/home/eddie/envs/deep/local/lib/python2.7/site-packages/chainer/variable.py", line 355, in <genexpr>
    for gx in gxs):
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Here gx is 
```
[[ 0.0001472   0.00014604  0.00015193 ...,  0.00015092  0.0001509
   0.00014626]
 [ 0.00014647  0.0001442   0.00015269 ...,  0.00015215  0.00015142
   0.00014504]
 [ 0.00014855  0.00014735  0.00015144 ...,  0.00015121  0.00015061
   0.00014711]
 ...,
 [ 0.00014409  0.00014379  0.00015338 ...,  0.00015306  0.00015099
   0.00014355]
 [ 0.00014459  0.00014202  0.00015292 ...,  0.00015324  0.00015215
   0.00014102]
 [ 0.00014621  0.00014452  0.00015207 ...,  0.00015231  0.00015252
   0.00014397]]
```

composed of np.float32

**Comment by unnonouno** [comment]
Sorry, this is a critical bug. I'll fix quickly.
